development:
  forest:
    emmanuellenadal:
      env_secret: 20178db3d204b14c3ffdd094bc14a0bcd16e51a08832bce5352f5a778c249eb0
      auth_secret: w7ILBNpHYfm0ycYtqtZj3A
      application_url: http://localhost:3000
    syan:
      env_secret: 5a061fd51523bf9bf853eaa33fbd7ecbc29e3d8681470fdae1c44972fdb9f70a
      auth_secret: 9408cf01dcea5b9514887e3d8c2662b6e83a8821dc695bf0
      application_url: http://localhost:3000
    luna:
      env_secret: 05949e4fd16231fd7a64d2cf06e7c1c2a329359b1a46e539723bbe62f7fed1e1
      auth_secret: dd66fac72bf4f084f8ca4a606d76d562594a2cfd372940d5
      application_url: http://localhost:3000
staging:
  forest:
    env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
    auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
    application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
production:
  forest:
    env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
    auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
    application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
